// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJY-vCFhRxv6yngjxXlcjo-BmXvSJQzAc',
    appId: '1:180788394887:web:9c3c5c1d1095548f17f122',
    messagingSenderId: '180788394887',
    projectId: 'flash-chat-flutter-d2b62',
    authDomain: 'flash-chat-flutter-d2b62.firebaseapp.com',
    storageBucket: 'flash-chat-flutter-d2b62.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlP0VozTppnqo_IAeJ1G0LpqfXoi_BTQo',
    appId: '1:180788394887:android:bb6fd6b6d329ba0d17f122',
    messagingSenderId: '180788394887',
    projectId: 'flash-chat-flutter-d2b62',
    storageBucket: 'flash-chat-flutter-d2b62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGgDDKHK2TP-vgBxgcJnXrhB3MJUBLNJ4',
    appId: '1:180788394887:ios:fd89b7e7cfffdd6817f122',
    messagingSenderId: '180788394887',
    projectId: 'flash-chat-flutter-d2b62',
    storageBucket: 'flash-chat-flutter-d2b62.appspot.com',
    iosBundleId: 'com.example.flashChat2',
  );
}
